# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1spjKu_ZCDFgF7bba3pcs2GIerTKsy-8O
"""

import pandas as pd
teachers=pd.DataFrame({
    "FISH":[ 'Qadamova Z'  , "xalilov d" , "qurbonova g" , 'jalilov m' , 'raxmativ r', 'turdimatov m' , 'abdullayeva m','xontorayev s','tillaboyeva g', 'jorayeva g'],
    'FANI':["Suniy intellekt asoslari" ,"Suniy intellekt asoslari" , "kompyuterni tashkil etish " , "kompyuterni tashkil etish " ,"kiberxavsizlik asoslari","kiberxavsizlik asoslari" ,'malumotlar tuzilmasi', 'malumotlar tuzilmasi','elektronika va sxemalar','elektronika va sxemalar'],
    "MASHGULOT TURI":['amaliy','maruza', 'amaliy', 'maruza' , 'amaliy', 'maruza'  , 'amaliy', 'maruza','amaliy', 'maruza' ],
    "Dars otish maxorati":['yaxshi','yaxshi', 'yaxshi', 'yaxshi','yaxshi','yaxshi','yaxshi','yaxshi','yaxshi','yaxshi']

})
print(teachers)

teachers.to_excel('681-23 oqituvchilari.xlsx')